% daviolinplot_demo.m  (revised to use tiledlayout/nexttile)
clear all
rng('default')

% prepare the same data as before
data1{1} = randn([30,1]);   % Humans
data1{2} = randn([40,1]);   % Dogs
data1{3} = randn([50,1]);   % God

data2 = [randn([30,4]); randn([30,4]); randn([30,4]); randn([30,4])];
group_inx = [ones(1,30), 2.*ones(1,30) 3.*ones(1,30) 4.*ones(1,30)];

data3{1} = randn([20,3]) + (0:0.5:1);    % Humans
data3{2} = randn([20,3]) - (2:2:6);      % Dogs

group_names     = {'Humans','Dogs','God','Potato'};
condition_names = {'Water','Land','Moon','Hyperspace'};
c = [0.45,0.80,0.69; 0.98,0.40,0.35; 0.55,0.60,0.79; 0.90,0.70,0.30];

% create a 3×3 grid (we have 7 examples; tiles 8–9 left blank)
figure('Name','daviolinplot_demo','WindowStyle','docked');
t = tiledlayout(3,3,'TileSpacing','compact','Padding','compact');

% Example 1: default half-violin + boxplot
nexttile
h = daviolinplot(data2(:,1),'groups',group_inx(1:90));
title('1: half-violin + box');

% Example 2: jitter + same-color boxes for 2×2
nexttile
h = daviolinplot(...
  data2(:,1:2),...
  'groups',group_inx(1:60),...
  'outsymbol','k+',...
  'boxcolors','same',...
  'scatter',1,...
  'jitter',1,...
  'xtlabels',condition_names,...
  'legend',group_names(1:2));
ylabel('Performance')
set(gca,'FontSize',10)
title('2: jittered scatter');

% Example 3: full-violins + white boxes
nexttile
h = daviolinplot(...
  data2(:,1:2),...
  'groups',group_inx(1:90),...
  'xtlabels',condition_names,...
  'violin','full',...
  'boxcolors','w');
ylabel('Performance')
legend([h.ds(1,:)],group_names(1:3))
set(gca,'FontSize',10)
title('3: full-violin + white box');

% Example 4: custom colors, box left, scatter center
nexttile
h = daviolinplot(...
  data2(:,1:2),...
  'groups',group_inx(1:90),...
  'outsymbol','k+',...
  'xtlabels',condition_names,...
  'colors',c,...
  'scatter',2,...
  'jitter',1,...
  'box',1,...
  'boxcolors','same',...
  'scattercolors','same',...
  'boxspacing',1.1,...
  'legend',group_names(1:3));
ylabel('Performance')
set(gca,'FontSize',10)
title('4: custom colors');

% Example 5: half-violin + dotplot histogram
nexttile
h = daviolinplot(...
  data2(:,1:2),...
  'groups',group_inx(1:90),...
  'colors',c,...
  'box',0,...
  'boxcolors','k',...
  'boxspacing',1.2,...
  'scatter',2,...
  'jitter',2,...
  'scattercolors','same',...
  'scattersize',14,...
  'bins',12,...
  'legend',group_names(1:3));
ylabel('Performance')
set(gca,'FontSize',10)
title('5: dotplot histogram');

% Example 6: cell-array input, black boxes, larger dots
nexttile
h = daviolinplot(...
  data1,...
  'colors',c,...
  'boxcolors','k',...
  'outliers',0,...
  'box',3,...
  'boxwidth',0.8,...
  'scatter',2,...
  'scattersize',35,...
  'jitter',2,...
  'xtlabels',group_names(1:3));
ylabel('Performance')
set(gca,'FontSize',10)
title('6: cell-array input');

% Example 7: white boxes, link lines, semi-transparent dots
nexttile
h = daviolinplot(...
  data3,...
  'groups',group_inx(1:90),...
  'colors',c,...
  'box',3,...
  'boxcolors','w',...     % note: in the function 'boxcolor' → 'boxcolors'
  'scatter',2,...
  'jitter',1,...
  'scattercolors','same',...
  'scattersize',10,...
  'scatteralpha',0.7,...
  'linkline',1,...
  'xtlabels',condition_names,...
  'legend',group_names(1:2));
ylabel('Performance')
set(h.sc,'MarkerEdgeColor','none')
set(gca,'FontSize',10)
title('7: link lines');

% tiles 8 & 9 are left empty