% B2K_tiledlayout_daviolinplot_withOverlay_demo03.m
% clear all
rng('default')

% — Data setup —
data1{1} = randn(30,1);
data1{2} = randn(40,1);
data1{3} = randn(50,1);

data2 = [randn(30,4);
         randn(30,4);
         randn(30,4);
         randn(30,4)];
group_inx = [ones(1,30), 2*ones(1,30), 3*ones(1,30), 4*ones(1,30)];

data3{1} = randn(20,3) + (0:0.5:1);
data3{2} = randn(20,3) - (2:2:6);

group_names     = {'Humans','Dogs','God','Potato'};
condition_names = {'Water','Land','Moon','Hyperspace'};

c = [0.45,0.80,0.69;
     0.98,0.40,0.35;
     0.55,0.60,0.79;
     0.90,0.70,0.30];

% — Create tiled layout —
% figure('Name','Overlay Demo 03','WindowStyle','docked');
figure
t = tiledlayout(3,3,'TileSpacing','compact','Padding','compact');

%% 1) Half-violins + separate features (left)
idx = 1:90;
nexttile
h = B2K_daviolinplot_withOverlay03( ...
      data2(idx,1), ...
      'groups', group_inx(idx), ...
      'violin','half', ...
      'overlay', true, ...
      'embedFeatures', false, ...
      'violinalpha', 0.5, ...
      'box',2, 'boxcolors','same', ...
      'whiskers',1, ...
      'outliers',1, ...
      'scatter',2,'scattercolors','same','scattersize',15, ...
      'linkline',1, ...
      'legend',{'G1','G2','G3'});
title('1: Half + separate features')
ylabel('Performance')
set(gca,'FontSize',10)

%% 2) Half-violins + jitter + separate
idx = 1:60;
nexttile
h = B2K_daviolinplot_withOverlay03( ...
      data2(idx,1:2), ...
      'groups', group_inx(idx), ...
      'violin','half', ...
      'overlay', true, ...
      'embedFeatures', false, ...
      'violinalpha',0.5, ...
      'scatter',1,'jitter',1,'scattercolors','same','outsymbol','k+', ...
      'box',2,'boxcolors','same','whiskers',1,'outliers',1, ...
      'linkline',1, ...
      'legend',{'G1','G2'});
title('2: Half+jit+separate')
set(gca,'FontSize',10)

%% 3) Full-violins + embedded features
idx = 1:90;
nexttile
h = B2K_daviolinplot_withOverlay03( ...
      data2(idx,1:2), ...
      'groups', group_inx(idx), ...
      'violin','full', ...
      'overlay', true, ...
      'embedFeatures', true, ...
      'violinalpha',0.5, ...
      'box',2,'boxcolors','w','whiskers',1,'outliers',1, ...
      'linkline',1, ...
      'legend',{'G1','G2','G3'}, ...
      'xtlabels',condition_names);
title('3: Full + embedded')
set(gca,'FontSize',10)

%% 4) Custom colors + separate
idx = 1:90;
nexttile
h = B2K_daviolinplot_withOverlay03( ...
      data2(idx,1:2), ...
      'groups', group_inx(idx), ...
      'violin','half', ...
      'colors',c, ...
      'overlay', true, ...
      'embedFeatures', false, ...
      'violinalpha',0.5, ...
      'box',1,'boxcolors','same','whiskers',1,'outliers',1, ...
      'scatter',2,'scattercolors','same','scattersize',12, ...
      'linkline',1, ...
      'legend',group_names(1:3), ...
      'xtlabels',condition_names);
title('4: Custom + separate')
set(gca,'FontSize',10)

%% 5) Dot-histogram + separate
idx = 1:90;
nexttile
h = B2K_daviolinplot_withOverlay03( ...
      data2(idx,1:2), ...
      'groups', group_inx(idx), ...
      'violin','half', ...
      'overlay', true, ...
      'embedFeatures', false, ...
      'violinalpha',0.5, ...
      'jitter',2,'bins',12, ...
      'box',0, ...
      'scatter',2,'scattercolors','same','scattersize',14, ...
      'linkline',1, ...
      'legend',group_names(1:3), ...
      'xtlabels',condition_names);
title('5: Dot-hist + separate')
set(gca,'FontSize',10)

%% 6) Cell-array + embedded
nexttile
h = B2K_daviolinplot_withOverlay03( ...
      data1, ...
      'violin','half', ...
      'overlay', true, ...
      'embedFeatures', true, ...
      'violinalpha',0.5, ...
      'colors',c, ...
      'box',3,'boxcolors','same','whiskers',1,'outliers',1, ...
      'scatter',2,'scattercolors','same','scattersize',35, ...
      'linkline',1, ...
      'legend',{'H','D','G'}, ...
      'xtlabels',group_names(1:3));
title('6: Cell-array + embedded')
set(gca,'FontSize',10)

%% 7) Link-lines + embedded
nexttile
h = B2K_daviolinplot_withOverlay03( ...
      data3, ...
      'violin','half', ...
      'overlay', true, ...
      'embedFeatures', true, ...
      'violinalpha',0.5, ...
      'colors',c, ...
      'box',2,'boxcolors','same','whiskers',1,'outliers',1, ...
      'scatter',2,'scattercolors','same','scattersize',10,'scatteralpha',0.7, ...
      'linkline',1, ...
      'legend',{'H','D'}, ...
      'xtlabels',condition_names);
title('7: Link-lines + embedded')
set(gca,'FontSize',10)

% Tiles 8 & 9 left blank